trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - name: toe
    value: "cephalopod"
  - name: "version_major"
    value: "0"
  - name: "version_minor"
    value: "0"
  - name: "version_revision"
    value: $[counter(variables['Version.Minor'], 0)]
  - name: version_number
    value: $(version_major).$(version_minor).$(version_revision)

steps:
- task: PowerShell@2
  displayName: 'Logging Command'
  inputs:
    targetType: 'inline'
    script: |
        $BuildName = $env:TOE +'_'+$env:VERSION_NUMBER +'_'+ $env:BUILD_SOURCEBRANCHNAME
        Write-Host "##vso[build.updatebuildnumber]$BuildName"

- task: PowerShell@2
  displayName: 'Build Number Using Logging Command'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "This is the variable for build number using vso[build.updatebuildnumber] logging command:"
      Write-Host "$(Build.BuildNumber)"

