trigger: none

pool:
  vmImage: ubuntu-latest

name: $(TeamProject)_$(ui.semver).$(Rev:r)

steps:
- task: PowerShell@2
  displayName: 'Pre-defined build number.'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "This is the predefined variable for build number using 'name' property:"
      Write-Host "$(Build.BuildNumber)"