trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - name: bob
    value: "toe"
  - name: "version_major"
    value: "0"
  - name: "version_minor"
    value: "0"
  - name: "version_revision"
    value: $[counter(variables['Version.Minor'], 0)]
  - name: version_number
    value: $(version_major).$(version_minor).$(version_revision)

name: $(TeamProject)_$(bob)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:r)

steps:
- task: PowerShell@2
  displayName: 'Logging Command'
  inputs:
    targetType: 'inline'
    script: |
        $BuildName = $env:BUILD_DEFINITIONNAME+'_'+$env:BOB +'_'+$env:VERSION_NUMBER +'_'+ $env:BUILD_SOURCEBRANCHNAME 
        Write-Host "##vso[build.updatebuildnumber]$BuildName"

      
- task: PowerShell@2
  displayName: 'New Build Number.'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "This is the predefined variable for build number using 'name' property:"
      Write-Host "$(Build.BuildNumber)"

