trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - name: toe
    value: "cephalopod"
  - name: "version_major"
    value: "0"
  - name: "version_minor"
    value: "0"
  - name: "version_revision"
    value: $[counter(variables['Version.Minor'], 0)]
  - name: version_number
    value: $(version_major).$(version_minor).$(version_revision)

name: $(TeamProject)_$(toe)_$(SourceBranchName)_$(version_number)

stages:
- stage: deploy
  jobs:
  - deployment: VarInName
    displayName: Var In Name
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'varinname'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: PowerShell@2
            displayName: 'Pre-defined build number.'
            inputs:
              targetType: 'inline'
              script: |
                Write-Host "This is the predefined variable for build number using 'name' property:"
                Write-Host "$(Build.BuildNumber)"