trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - name: toe
    value: "cephalopod"
  - name: "version_major"
    value: "0"
  - name: "version_minor"
    value: "0"
  - name: "version_revision"
    value: $[counter(variables['Version.Minor'], 0)]

stages:
- stage: build
  jobs:
  - job: Build
    steps:
    - task: PowerShell@2
      displayName: 'Logging Command'
      inputs:
        targetType: 'inline'
        script: |
            $version_number = $env:VERSION_MAJOR+'.'+$env:VERSION_MINOR+'.'+$env:VERSION_REVISION
            $BuildName = $env:TOE +'_'+$version_number +'_'+ $env:BUILD_SOURCEBRANCHNAME
            Write-Host "##vso[build.updatebuildnumber]$BuildName"

- stage: deploy
  jobs:
  - deployment: VarLoggingCmd
    displayName: Var Logging Cmd
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'varloggingcmd'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: PowerShell@2
            displayName: 'Build Number Using Logging Command'
            inputs:
              targetType: 'inline'
              script: |
                Write-Host "This is the variable for build number using vso[build.updatebuildnumber] logging command:"
                Write-Host "$(Build.BuildNumber)"

