trigger: none

pool:
  vmImage: ubuntu-latest

name: $(TeamProject)_cephalopod_$(ui.semver).$(Rev:r)_$(Build.SourceBranchName)

stages:
- stage: deploy
  jobs:
  - deployment: UsingUI
    displayName: Using UI
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'usingui'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: PowerShell@2
            displayName: 'Pre-defined build number.'
            inputs:
              targetType: 'inline'
              script: |
                Write-Host "This is the predefined variable for build number using 'name' property:"
                Write-Host "$(Build.BuildNumber)"
