trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - name: toe
    value: "cephalopod"
  - name: "version_major"
    value: "0"
  - name: "version_minor"
    value: "0"

name: $(TeamProject)_$(toe)_$(version_major).$(version_minor).$(Rev:r)_$(BuildSourceBranchName)

stages:
- stage: build
  jobs:
  - job: Build
    steps:
    - task: PowerShell@2
      displayName: 'Build Number Using Name Property'
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "This is the variable for build number using 'name' property:"
          Write-Host "$(Build.BuildNumber)"
    - task: PowerShell@2
      displayName: 'Logging Command'
      inputs:
        targetType: 'inline'
        script: |
            $version_number = $env:VERSION_MAJOR+'.'+$env:VERSION_MINOR+'.'+$env:VERSION_REVISION
            $BuildName = $env:TOE +'_'+$version_number +'_'+ $env:BUILD_SOURCEBRANCHNAME
            Write-Host "##vso[build.updatebuildnumber]$BuildName"

- stage: deploy
  jobs:
  - deployment: VarNameLogging
    displayName: Var Name & Logging Cmd
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'varnamelogging'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: PowerShell@2
            displayName: 'Build Number Using Logging Command'
            inputs:
              targetType: 'inline'
              script: |
                Write-Host "This is the variable for build number using vso[build.updatebuildnumber] logging command:"
                Write-Host "$(Build.BuildNumber)"
                Write-Host "This overwrites what is set using 'name' property in the azure devops yaml."

