trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: PowerShell@2
  displayName: 'Pre-defined build number.'
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "This is the predefined variable for build number:"
      Write-Host "$(Build.BuildNumber)"
